# .readthedocs.yml

version: 2

sphinx:
    builder: html
    configuration: docs/conf.py

build:
  image: latest
  apt_packages:
    - iputils-ping
    - build-essential
    - gfortran
    - csh
    - zsh

formats: all

python:
  version: 3.7
  install:
    - requirements: requirements.txt
    - requirements: docs/requirements.txt
