# .readthedocs.yml

version: 2

sphinx:
    builder: html
    configuration: docs/conf.py

build:
  image: latest

formats: all

python:
  version: 3.6
  install:
    - requirements: requirements.txt
    - requirements: docs/requirements.txt
