# .readthedocs.yml

version: 2

sphinx:
    builder: html
    configuration: docs/conf.py
    fail_on_warning: false

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.7"
  apt_packages:
    - iputils-ping
    - build-essential
    - gfortran
    - csh
    - zsh
    - tree

formats:
  - pdf

python:
  install:
    - requirements: requirements.txt
    - requirements: docs/requirements.txt
