matrix:
- name: Python
  aspell:
    ignore-case: true
    lang: en
  dictionary:
    wordlists:
    - .wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.python:
      comments: true
      docstrings: true
      group_comments: false
      decode_escapes: true
      strings: false
      string_types: fu
  sources:
  - '**/*.py'
  default_encoding: utf-8

- name: Markdown
  aspell:
    ignore-case: true
    lang: en
  dictionary:
    wordlists:
    - .wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.markdown:
  - pyspelling.filters.html:
      comments: false
      ignores:
      - code
      - pre
  sources:
  - '**/*.md'
  default_encoding: utf-8
