name: Buildtest Command Line Feature Request
description: Feature request for buildtest program
title: "[FEATURE]: "
labels: [feature, triage]
assignees:
  - shahzebsiddiqui
body:
  - type: textarea
    id: feature_description
    attributes:
      label: Please describe your feature request
      description: Please provide a detailed summary of the feature request including name of buildtest command (buildtest build) and options including intended behavior
    validations:
      required: true

  - type: checkboxes
    id: slackterms
    attributes:
      label: Post question in Slack
      options:
        - label: I agree that I posted my question in [slack](https://hpcbuildtest.slack.com/) before creating this issue
          required: true

  - type: checkboxes
    id: issueterms
    attributes:
      label: Is there an existing issue
      options:
        - label: I confirm there is no existing [issue](https://github.com/buildtesters/buildtest/issues) for this issue
          required: true