system:
  generic:
    hostnames:
    - .*
    description: Generic System
    moduletool: N/A
    poolsize: 1
    pager: false
    buildspecs:
      rebuild: false
      count: 15
      format: name,description
      terse: false
    report:
      count: 25
      terse: false
      format: name,id,state,runtime,returncode
      latest: true
      oldest: false
    executors:
      local:
        bash:
          description: submit jobs on local machine using bash shell
          shell: bash
        sh:
          description: submit jobs on local machine using sh shell
          shell: sh
        csh:
          description: submit jobs on local machine using csh shell
          shell: csh
        zsh:
          description: submit jobs on local machine using zsh shell
          shell: zsh
    compilers:
      compiler:
        gcc:
          builtin_gcc:
            cc: gcc
            fc: gfortran
            cxx: g++
    cdash:
      url: https://my.cdash.org/
      project: buildtest
      site: generic
      buildname: tutorials
    profiles:
      python-tests:
        tags:
        - python
        testdir: /Users/siddiq90/Documents/github/buildtest/var/tests
      profile-demo:
        buildspecs:
        - /Users/siddiq90/Documents/github/buildtest/tutorials/job_dependency
        exclude-buildspecs:
        - tutorials/job_dependency/ex1.yml
        tags:
        - python
        exclude-tags:
        - network
        executors:
        - generic.local.csh
        rebuild: 2
        limit: 10
        account: dev
        procs:
        - 2
        - 4
        nodes:
        - 1
        - 2
        testdir: /Users/siddiq90/Documents/github/buildtest/var/tests
        timeout: 10
      filter_maintainers:
        buildspecs:
        - /Users/siddiq90/Documents/github/buildtest/tutorials
        module-purge: false
        testdir: /Users/siddiq90/Documents/github/buildtest/var/tests
        filter:
          maintainers:
          - '@shahzebsiddiqui'
      filter_tags:
        buildspecs:
        - /Users/siddiq90/Documents/github/buildtest/tutorials
        module-purge: false
        testdir: /Users/siddiq90/Documents/github/buildtest/var/tests
        filter:
          tags:
          - python
      filter_type:
        buildspecs:
        - /Users/siddiq90/Documents/github/buildtest/tutorials
        module-purge: false
        limit: 5
        testdir: /Users/siddiq90/Documents/github/buildtest/var/tests
        filter:
          type:
          - script
          - compiler
      demo:
        buildspecs:
        - /Users/siddiq90/Documents/github/buildtest/tutorials/shell_examples.yml
        module-purge: true
        testdir: /Users/siddiq90/Documents/github/buildtest/var/tests
        executor-type: local
      profile-2:
        buildspecs:
        - /Users/siddiq90/Documents/github/buildtest/tutorials/job_dependency
        exclude-buildspecs:
        - tutorials/job_dependency/ex1.yml
        tags:
        - python
        exclude-tags:
        - network
        executors:
        - generic.local.csh
        rebuild: 2
        limit: 10
        account: dev
        procs:
        - 2
        - 4
        nodes:
        - 1
        - 2
        testdir: /Users/siddiq90/Documents/github/buildtest/var/tests
        timeout: 10
        executor-type: local
      filter_profile:
        buildspecs:
        - /Users/siddiq90/Documents/github/buildtest/tutorials
        testdir: /Users/siddiq90/Documents/github/buildtest/var/tests
        filter:
          tags:
          - pass
          maintainers:
          - '@shahzebsiddiqui'
          type:
          - script
