name: Regression Test in buildtest tutorial container

on:
  pull_request:
    branches: [ devel ]

jobs:
  buildtest_tutorial_container:
    runs-on: ubuntu-latest
    container: shahzebsiddiqui/buildtest_spack
    steps:
      - name: debug in container
        run: | 
          env
          which git
          git --version
          cat ~/.bashrc
          
        
      - uses: actions/checkout@v2
      - name: regression test in container
        run: |
          which git
          git --version
          env
          cd $GITHUB_WORKSPACE
          ls -la $GITHUB_WORKSPACE
          ls -la $HOME
          . buildtest/scripts/spack_container/setup.sh
          module avail
          git log HEAD
          python scripts/regtest.py

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 30

