name: Regression Test in buildtest tutorial container

on:
  pull_request:
    branches: [ devel ]

jobs:      
  buildtest_tutorial_container:
    runs-on: ubuntu-latest
    container: 
      image: shahzebsiddiqui/buildtest_spack
      options: "-it"
    steps:
      - name: debug in container
        run: | 
          env
          whoami
          id
          which git
          git --version        
          ls -la $HOME
          echo $HOME
          # . ~/spack/share/spack/setup-env.sh
          # spack load git@2.29.0          
      - uses: actions/checkout@v2
      - name: regression test in container
        run: |
          which git
          git --version
          env
          cd $GITHUB_WORKSPACE
          ls -la $GITHUB_WORKSPACE
          ls -la $HOME
          . buildtest/scripts/spack_container/setup.sh
          module avail
          git log HEAD
          python scripts/regtest.py

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 30

