name: Build and Test Tutorial Container

on:
  pull_request:
    branches: [ devel ]

jobs:  
  build_container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/buildtesters/buildtest_spack:latest
          context: scripts/spack_container
          push: true
    
  buildtest_tutorial_container:
    needs: build_container
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/buildtesters/buildtest_spack
      options: "-it"
    steps:
      - name: debug in container
        run: | 
          env
          whoami
          id
          which git
          git --version        
          ls -la $HOME
          echo $HOME
          shopt -q login_shell && echo 'Login shell' || echo 'Not login shell'

      - uses: actions/checkout@v2
      - name: regression test in container
        run: |
          which git
          git --version
          env
          cd $GITHUB_WORKSPACE
          ls -la $GITHUB_WORKSPACE
          ls -la $HOME
          . buildtest/scripts/spack_container/setup.sh
          module avail
          git log HEAD
          python scripts/regtest.py
