name: Regression Test in buildtest tutorial container

on:
  pull_request:
    branches: [ devel ]

jobs:
  buildtest_tutorial_container:
    runs-on: ubuntu-latest
    container:
      image: docker://shahzebsiddiqui/buildtest_spack
    steps:
      - name: regressiontest
        run: |
          ls -l
          whoami
