name: Style Checks

on:
  push:
    branches:
      - master
      - devel
  pull_request:
      branches:
        - master
        - devel

jobs:
  style_checks:
    runs-on: ubuntu-latest
    steps:

      # use isort github action see https://pycqa.github.io/isort/docs/configuration/github_action.html
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.8

      - name: Check imports with pyflakes
        run: |
          pip install pyflakes
          pyflakes buildtest tests scripts

      - name: Running isort check
        uses: jamescurtin/isort-action@master
        with:
          #requirementsFiles: "requirements.txt docs/requirements.txt"
          sortPaths: "buildtest tests docs"

      - name: Running black check
      # use black github action see https://black.readthedocs.io/en/stable/integrations/github_actions.html
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "buildtest tests scripts"
          version: "~= 22.0"

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: devel
          #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}